import turtle

turtle.speed(1000)
turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'blue')
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.right(180)
turtle.forward(100)
turtle.left(50)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 130)
turtle.end_fill()

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'purple')
turtle.begin_fill()
turtle.right(60)
turtle.forward(100)
turtle.right(90)
turtle.circle(-100, 30)
turtle.end_fill()

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'green')
turtle.begin_fill()
turtle.left(165)
turtle.forward(100)
turtle.right(90)
turtle.circle(-100, 45)
turtle.end_fill()

turtle.up()
turtle.circle(-100, 30)

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'orange')
turtle.begin_fill()
turtle.left(215)
turtle.forward(100)
turtle.right(90)
turtle.circle(-100, 50)
turtle.end_fill()

turtle.up()
turtle.circle(-100, 75)

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'red')
turtle.begin_fill()
turtle.left(215)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 105)
turtle.end_fill()

turtle.color('black')
turtle.up()
turtle.setposition(90, 160)
turtle.write('A', False, 'left', ("Arial", 10, "normal"))
turtle.setposition(0, -30)
turtle.write('B', False, 'left', ("Arial", 10, "normal"))
turtle.setposition(-120, 70)
turtle.write('C', False, 'left', ("Arial", 10, "normal"))
turtle.setposition(-90, 160)
turtle.write('D', False, 'left', ("Arial", 10, "normal"))
turtle.setposition(-30, 200)
turtle.write('E', False, 'left', ("Arial", 10, "normal"))

turtle.done()
