import turtle

turtle.pensize(10)

turtle.up()
turtle.setposition(25, 80)
turtle.down()
turtle.color('SkyBlue')
turtle.right(90)
turtle.forward(90)
turtle.right(180)
turtle.forward(60)
turtle.right(90)
turtle.forward(90)
turtle.right(180)
turtle.forward(170)
turtle.right(180)
turtle.forward(80)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(85)
turtle.right(180)
turtle.forward(160)

turtle.up()
turtle.setposition(-25, 80)
turtle.down()
turtle.left(105)
turtle.forward(93)
turtle.right(105)

turtle.up()
turtle.setposition(75, 80)
turtle.down()
turtle.left(75)
turtle.forward(93)

turtle.left(105)
turtle.up()
turtle.setposition(-100, 100)
turtle.down()
turtle.color('RoyalBlue4')
turtle.forward(25)
turtle.right(75)
turtle.forward(100)
turtle.right(180)
turtle.forward(80)
turtle.right(105)
turtle.forward(200)
turtle.right(105)
turtle.forward(100)
turtle.right(75)
turtle.forward(150)
turtle.left(105)
turtle.forward(25)
turtle.left(75)
turtle.forward(140)

turtle.up()
turtle.setposition(-25, -100)
turtle.down()
turtle.color('RoyalBlue4', 'RoyalBlue4')
turtle.begin_fill()
turtle.pensize(1)
turtle.circle(18)
turtle.end_fill()

turtle.up()
turtle.setposition(75, -100)
turtle.down()
turtle.color('RoyalBlue4', 'RoyalBlue4')
turtle.begin_fill()
turtle.pensize(1)
turtle.circle(18)
turtle.end_fill()

turtle.done()
